"use client";
import { useState } from 'react';
import type { OperationReport, Explore } from './types';
import styles from './operation.module.css';
import { timeText } from './TimeValue';
const n = (v: number | null | undefined) => v == null ? 'Sin datos' : v.toLocaleString('es-MX', { maximumFractionDigits: 1 });
const min = (v: number | null) => v === null ? 'Sin datos' : n(v) + ' min';
export function DestinationPanel({ r, explore }: { r: OperationReport; explore: Explore }) {
  const [selected, setSelected] = useState('lathe'), [page, setPage] = useState(1);
  const d = r.destinations.find(x => x.key === selected)!;
  const clients = [...d.clients].sort((a, b) => b.clientDelayMinutes - a.clientDelayMinutes || b.concluded - a.concluded);
  const pages = Math.max(1, Math.ceil(clients.length / 10));
  const drill = (filter = 'all', state = '') => explore(filter, '', '', state, { group: 'destination', groupKey: d.key, label: 'Hacia ' + d.label });
  return <section className={styles.card}><h2>Entradas a torno y lavado</h2><p className={styles.note}>Entradas = traslados CONCLUIDOS hacia Torno o Lavado, identificados por la vía de destino o por el servicio marcado cuando falta esa vía. Detenidos y cancelados cuentan como intentos y retraso del cliente. Los tiempos miden el traslado; no la duración del servicio dentro de torno o lavado.</p><div className={styles.subnav}>{r.destinations.map(x => <button type="button" key={x.key} aria-pressed={selected === x.key} onClick={() => { setSelected(x.key); setPage(1); }}>{x.label}</button>)}</div>
    <div className={styles.resolutionGrid}><div><span>Entradas concluidas a {d.label.toLowerCase()}</span><strong>{n(d.concluded)}</strong><button type="button" className={styles.textButton} onClick={() => drill('all', 'CONCLUIDO')}>Ver entradas</button></div><div><span>Intentos detenidos / cancelados</span><strong>{n(d.stopped)} / {n(d.cancelled)}</strong><small>{d.total} solicitudes hacia esta vía</small></div><div><span>Retraso del cliente</span><strong>{min(d.clientDelayMinutes)}</strong><button type="button" className={styles.textButton} onClick={() => drill('client_delay')}>Ver {d.clientDelayN} intentos con tiempo</button><small>{d.clientDelayMissing} con fechas por completar</small></div><div><span>Espera promedio de entradas</span><strong>{min(d.completed.waitAverage)}</strong><small>{d.completed.waitN} intervalos válidos</small></div><div><span>Ejecución promedio de entradas</span><strong>{min(d.completed.executionAverage)}</strong><small>{d.completed.executionN} intervalos válidos</small></div><div><span>Ejecución de detenidos y cancelados</span><strong>{min(d.clientDelayN ? d.clientDelayMinutes / d.clientDelayN : null)}</strong><small>Promedio inicio → detención/cancelación</small></div></div>
    <p className={styles.note}>{n(d.completedVia)} entradas con vía de destino registrada y {n(d.completedService)} identificadas por el servicio. Cada movimiento cuenta una sola vez.</p><button type="button" className={styles.textButton} onClick={() => drill('destination_service', 'CONCLUIDO')}>Ver entradas identificadas por servicio</button>
    <h3>Por empresa y cliente</h3><div className={styles.tableScroll}><table><thead><tr><th>Empresa / cliente</th><th>Entradas concluidas</th><th>Detenidos</th><th>Cancelados</th><th>Retraso del cliente</th><th>Ejecución promedio de entradas</th><th>Detalle</th></tr></thead><tbody>{clients.slice((page - 1) * 10, page * 10).map(c => <tr key={c.key}><th scope="row">{c.label}</th><td>{c.concluded}</td><td>{c.stopped}</td><td>{c.cancelled}</td><td>{timeText(!c.clientDelayN && c.clientDelayMissing ? null : c.clientDelayMinutes)}<small>{c.clientDelayMissing} con fechas pendientes</small></td><td>{min(c.completed.executionAverage)}</td><td><button type="button" className={styles.textButton} onClick={() => explore('all', '', '', '', { group: 'destination_client', groupKey: d.key + ':' + c.key, label: d.label + ': ' + c.label })}>Ver movimientos</button></td></tr>)}</tbody></table></div>{!clients.length && <p>No hay solicitudes hacia esta vía con los filtros aplicados.</p>}<div className={styles.pager}><span>{clients.length} grupos · Página {page} de {pages}</span><div><button type="button" disabled={page <= 1} onClick={() => setPage(page - 1)}>Anterior</button><button type="button" disabled={page >= pages} onClick={() => setPage(page + 1)}>Siguiente</button></div></div>
  </section>;
}
