"use client";
import { useEffect, useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowRight, CheckCircle2, Clock3, FileSpreadsheet, FileText, Info, RefreshCw, Search, TrainFront, TriangleAlert } from 'lucide-react';
import type { Group, Metrics, OperationReport as Report, DetailRow, Explore, ExploreGroup } from './types';
import { DurationBands, CompanyClients, IncidentResolution, ImpactSummary, ClientDelaySummary, RetryHistory, bandLabels } from './DecisionPanels';
import { initialFilters, localDay, shiftDay, useOperationReport, useReportDetail } from './useOperationReport';
import styles from './operation.module.css';
import { timeText } from './TimeValue';
import { DestinationPanel } from './DestinationPanel';

const n = (value: number | null, digits = 1) => value === null ? 'Sin datos' : value.toLocaleString('es-MX', { maximumFractionDigits: digits });
const mins = (value: number | null) => value === null ? 'Sin datos' : `${n(value)} min`;
const pct = (value: number | null) => value === null ? 'Sin datos' : `${n(value)}%`;
const date = (value: string | null) => value ? new Intl.DateTimeFormat('es-MX', { timeZone: 'America/Mexico_City', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Sin registro';
type Tab = 'summary' | 'times' | 'companies' | 'incidents' | 'detail' | 'quality';
const tabs: { id: Tab; label: string }[] = [{ id: 'summary', label: 'Resumen' }, { id: 'times', label: 'Tiempos y horarios' }, { id: 'companies', label: 'Empresas, clientes y vías' }, { id: 'incidents', label: 'Incidentes y resolución' }, { id: 'detail', label: 'Ver movimientos' }, { id: 'quality', label: 'Calidad y definiciones' }];
function Empty({ children = 'No hay movimientos con estos filtros.' }: { children?: React.ReactNode }) { return <div className={styles.empty}><Search size={25} /><p>{children}</p><span>Prueba otro periodo o quita los filtros de empresa y localidad.</span></div>; }
function Section({ title, note, children }: { title: string; note?: string; children: React.ReactNode }) { return <section className={styles.card}><h2>{title}</h2>{note && <p className={styles.note}>{note}</p>}{children}</section>; }
function KPI({ title, value, note, icon }: { title: string; value: string; note: string; icon: React.ReactNode }) { return <div className={styles.kpi}><div className={styles.kpiLabel}>{icon}{title}</div><div className={styles.kpiValue}>{value}</div><p>{note}</p></div>; }
function GroupTable({ groups, title, note, onExplore }: { groups: Group[]; title: string; note: string; onExplore?: (g: Group, filter?: string) => void }) {
  const [search, setSearch] = useState(''), [sort, setSort] = useState('total'), [page, setPage] = useState(1);
  const [view, setView] = useState('duration');
  const rows = useMemo(() => groups.filter(g => g.label.toLocaleLowerCase('es-MX').includes(search.toLocaleLowerCase('es-MX'))).sort((a, b) => {
    if (sort === 'label') return a.label.localeCompare(b.label);
    const key = sort as 'total' | 'waitAverage' | 'incidentRate' | 'affected' | 'durationShort' | 'durationLong' | 'excessMinutes' | 'clientDelayMinutes';
    return (b[key] ?? -1) - (a[key] ?? -1) || a.label.localeCompare(b.label);
  }), [groups, search, sort]);
  const pages = Math.max(1, Math.ceil(rows.length / 10)), current = Math.min(page, pages);
  return <Section title={title} note={note}><div className={styles.subnav}><button type="button" aria-pressed={view === 'duration'} onClick={() => setView('duration')}>Duración e incidentes</button><button type="button" aria-pressed={view === 'times'} onClick={() => setView('times')}>Espera y retraso del cliente</button></div><div className={styles.tableTools}><label>Buscar grupo<input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Nombre o referencia" /></label><label>Ordenar por<select value={sort} onChange={e => { setSort(e.target.value); setPage(1); }}><option value="clientDelayMinutes">Mayor retraso del cliente</option><option value="total">Más movimientos</option><option value="waitAverage">Mayor espera promedio</option><option value="affected">Más movimientos con incidentes</option><option value="incidentRate">Mayor tasa de incidentes</option><option value="durationShort">Más casos menores de 10</option><option value="durationLong">Más casos mayores de 30</option><option value="excessMinutes">Más minutos sobre 30</option><option value="label">Nombre</option></select></label></div>
    {rows.length ? <><div className={styles.tableScroll} tabIndex={0} role="region" aria-label={title}><table><caption>{title}. Aceptable usa los evaluados; incidentes usa las solicitudes de cada grupo.</caption><thead><tr><th>Grupo</th><th>Movimientos</th>{view === 'duration' ? <><th>Menos de 10</th><th>10 a 30</th><th>Más de 30</th><th>Detenidos / cancelados</th></> : <><th>Espera promedio</th><th>Duración promedio</th></>}<th>Con incidentes</th>{view === 'times' && <><th>Retraso del cliente</th><th>Minutos sobre 30</th><th>Min. con incidentes</th></>}{onExplore && <th>Detalle</th>}</tr></thead><tbody>{rows.slice((current - 1) * 10, current * 10).map(g => <tr key={g.key}><th scope="row">{g.label}{g.smallSample && <small>Muestra menor de 30</small>}</th><td>{n(g.total, 0)}</td>{view === 'duration' && (['short', 'acceptable', 'long'] as const).map((band, index) => <td key={band}>{onExplore ? <button type="button" className={styles.bandCount} data-band={band} onClick={() => onExplore(g, band)} aria-label={`${bandLabels[band]}: ${g.label}`}>{n([g.durationShort, g.durationAcceptable, g.durationLong, g.durationUnassessed][index], 0)}</button> : n([g.durationShort, g.durationAcceptable, g.durationLong, g.durationUnassessed][index], 0)}{band === 'acceptable' && <small>{pct(g.acceptableRate)}</small>}</td>)}{view === 'duration' && <td>{g.stopped} / {g.cancelled}</td>}{view === 'times' && <><td>{mins(g.waitAverage)}<small>{n(g.waitN, 0)} intervalos</small></td><td>{mins(g.executionAverage)}<small>{n(g.executionN, 0)} evaluados</small></td></>}<td>{onExplore ? <button type="button" className={styles.textButton} onClick={() => onExplore(g, 'incident')}>{n(g.affected, 0)}</button> : n(g.affected, 0)}<small>{pct(g.incidentRate)}</small></td>{view === 'times' && <><td>{onExplore ? <button type="button" className={styles.textButton} onClick={() => onExplore(g, 'client_delay')}>{mins(g.clientDelayMinutes)}</button> : mins(g.clientDelayMinutes)}<small>{g.clientDelayN} intentos · {g.clientDelayMissing} sin fechas</small></td><td>{mins(g.excessMinutes)}</td><td>{mins(g.incidentMinutes)}</td></>}{onExplore && <td><button type="button" className={styles.textButton} onClick={() => onExplore(g)}>Ver <ArrowRight size={14} /></button></td>}</tr>)}</tbody></table></div><p className={styles.note}>Los tiempos corresponden al movimiento completo. Exceso sobre 30 y minutos con incidentes pueden coincidir; no se suman ni atribuyen una causa.</p><Pager page={current} pages={pages} total={rows.length} setPage={setPage} noun="grupos" /></> : <Empty />}
  </Section>;
}
function Pager({ page, pages, total, setPage, noun }: { page: number; pages: number; total: number; setPage: (p: number) => void; noun: string }) { return <div className={styles.pager}><span>{n(total, 0)} {noun} · Página {page} de {pages}</span><div><button type="button" disabled={page <= 1} onClick={() => setPage(page - 1)}>Anterior</button><button type="button" disabled={page >= pages} onClick={() => setPage(page + 1)}>Siguiente</button></div></div>; }
function Change({ current, previous, points = false, covered }: { current: number | null; previous: number | null; points?: boolean; covered: boolean }) {
  if (!covered || current === null || previous === null) return <span className={styles.muted}>No comparable</span>;
  if (!points && previous === 0) return <span className={styles.muted}>Sin base anterior</span>;
  const change = points ? current - previous : (current - previous) / previous * 100;
  return <span>{change > 0 ? '+' : ''}{n(change)} {points ? 'puntos' : '%'}</span>;
}
function Comparison({ report: r }: { report: Report }) {
  const defs: { key: keyof Metrics; label: string; format: (x: number | null) => string; points?: boolean }[] = [
    { key: 'acceptableRate', label: 'Duración aceptable: 10 a 30 min', format: pct, points: true }, { key: 'durationShort', label: 'Duración menor de 10 min', format: v => n(v, 0) }, { key: 'durationLong', label: 'Duración mayor de 30 min', format: v => n(v, 0) }, { key: 'total', label: 'Solicitudes', format: v => n(v, 0) }, { key: 'waitMedian', label: 'Tiempo habitual hasta comenzar', format: mins }, { key: 'targetRate', label: `Iniciados dentro de ${r.meta.target} min`, format: pct, points: true }, { key: 'incidentRate', label: 'Movimientos con incidentes', format: pct, points: true },
  ];
  return <Section title="¿Qué cambió frente al periodo anterior?" note={`Anterior: ${date(r.meta.previousStart)} a ${date(r.meta.previousEndExclusive)} (fin exclusivo). Mismos filtros e igual duración.`}><div className={styles.tableScroll}><table><thead><tr><th>Indicador</th><th>Seleccionado</th><th>Anterior</th><th>Cambio</th></tr></thead><tbody>{defs.map(d => <tr key={d.key}><th scope="row">{d.label}</th><td>{d.format(r.summary[d.key])}</td><td>{d.format(r.baseline[d.key])}</td><td><Change current={r.summary[d.key]} previous={r.baseline[d.key]} points={d.points} covered={r.meta.comparisonCovered} /></td></tr>)}</tbody></table></div><p className={styles.note}>Los cambios describen los registros disponibles. No prueban una mejora o deterioro por sí solos; revisa volumen, tipo y cobertura.</p></Section>;
}
function DailyChart({ groups }: { groups: Group[] }) {
  if (!groups.length) return <Empty />;
  const max = Math.max(1, ...groups.map(g => g.total)), width = 800, height = 180;
  const points = groups.map((g, i) => `${35 + i / Math.max(groups.length - 1, 1) * (width - 60)},${height - 25 - g.total / max * (height - 50)}`).join(' ');
  return <div className={styles.trend}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Solicitudes por día. ${groups.length} días representados. Máximo ${max} solicitudes.`}><title>Solicitudes por día local</title>{[0, .5, 1].map(t => <g key={t}><line x1="35" x2="775" y1={height - 25 - t * (height - 50)} y2={height - 25 - t * (height - 50)} stroke="var(--op-line)" /><text x="4" y={height - 20 - t * (height - 50)} fontSize="11" fill="var(--op-muted)">{Math.round(t * max)}</text></g>)}<polyline fill="none" stroke="var(--op-accent)" strokeWidth="3" points={points} />{groups.length === 1 && <circle cx="35" cy={height - 25 - groups[0].total / max * (height - 50)} r="4" fill="var(--op-accent)" />}</svg><div><span>{groups[0].label}</span><span>{groups.at(-1)?.label}</span></div><details><summary>Consultar valores de la gráfica</summary><div className={styles.tableScroll}><table><thead><tr><th>Día</th><th>Solicitudes</th></tr></thead><tbody>{groups.map(g => <tr key={g.key}><td>{g.label}</td><td>{g.total}</td></tr>)}</tbody></table></div></details></div>;
}
function TimeReport({ r, explore }: { r: Report; explore: Explore }) {
  const k = r.summary;
  return <><Section title="¿Cuánto esperamos y cuánto dura el movimiento?" note="Tiempo habitual: la mitad de los casos tardó ese tiempo o menos. El valor para 9 de cada 10 describe los casos más lentos."><div className={styles.twoColumns}><div className={styles.timeBlock}><Clock3 /><h3>Antes de comenzar</h3><strong>{mins(k.waitMedian)}</strong><p>Tiempo habitual desde la solicitud hasta el inicio.</p><b>{mins(k.waitP90)} para 9 de cada 10</b><p className={styles.note}>{k.waitN} intervalos válidos. {k.missingWait} solicitudes sin tiempo calculable.</p></div><div className={styles.timeBlock}><TrainFront /><h3>Durante el movimiento</h3><strong>{mins(k.executionMedian)}</strong><p>Tiempo habitual desde el inicio hasta conclusión, detención o cancelación.</p><b>{mins(k.executionP90)} para 9 de cada 10</b><p className={styles.note}>{k.executionN} intervalos válidos. Incluye pausas; no es tiempo neto de trabajo.</p></div></div></Section>
    <Section title="Promedios del periodo" note="El promedio suma los tiempos válidos y los divide entre su cantidad. Los casos extremos pueden elevarlo."><div className={styles.twoColumns}><div><h3>Espera antes de iniciar</h3><strong>{mins(k.waitAverage)}</strong><p>{k.waitN} intervalos válidos; {k.missingWait} sin tiempo calculable.</p></div><div><h3>Duración hasta el corte</h3><strong>{mins(k.executionAverage)}</strong><p>{k.executionN} intervalos válidos.</p></div></div></Section>
    <ClientDelaySummary r={r} explore={explore} /><RetryHistory r={r} explore={explore} /><DurationBands metrics={k} explore={explore} /><ImpactSummary r={r} />
    <Section title={`Objetivo de espera: comenzar en ${r.meta.target} minutos`} note="Este objetivo se aplica a la espera previa. El rango de 10 a 30 se aplica a la duración del movimiento."><div className={styles.goal}><strong>{pct(k.targetRate)}</strong><span>{k.withinTarget} de {k.waitN} movimientos con espera válida comenzaron dentro del objetivo.</span></div>{k.targetRate !== null && <progress max="100" value={k.targetRate} aria-label="Proporción dentro del objetivo" />}<p className={styles.note}>{k.pending} solicitudes del periodo siguen pendientes. Las que no tienen inicio no entran en este porcentaje.</p><button type="button" className={styles.textButton} onClick={() => explore('late')}>Revisar esperas mayores de {r.meta.target} min <ArrowRight size={16} /></button></Section>
    <Section title="¿A qué horas recibimos más solicitudes?" note={`Hora de solicitud en ${r.meta.zone}. El color describe volumen, no gravedad.`}><div className={styles.hours}>{r.hours.map(h => <div key={h.key} title={`${h.label}: ${h.total} solicitudes; espera habitual ${mins(h.waitMedian)}`}><span>{h.label}</span><div className={styles.hourTrack}><div style={{ height: `${Math.max(h.total ? 3 : 0, h.total / Math.max(1, ...r.hours.map(x => x.total)) * 100)}%` }} /></div><b>{h.total}</b></div>)}</div></Section>
    <GroupTable title="Atención por turno" note="Turnos de la aplicación: 07-15, 15-23 y 23-07. Agrupados por hora de solicitud; no indican asistencia del personal." groups={r.shifts} />
    <GroupTable title="Detalle por hora" note="Compara volumen y tiempos. Una espera alta requiere revisar la secuencia operativa antes de atribuir una causa." groups={r.hours} />
  </>;
}
function IncidentReport({ r }: { r: Report }) {
  const [search, setSearch] = useState(''), [page, setPage] = useState(1);
  const items = r.incidents.frequent.filter(i => i.description.toLocaleLowerCase('es-MX').includes(search.toLocaleLowerCase('es-MX')));
  return <><div className={styles.kpis}><KPI title="Movimientos con incidentes" value={n(r.summary.affected, 0)} note={`${pct(r.summary.incidentRate)} de las ${r.summary.total} solicitudes.`} icon={<TriangleAlert size={18} />} /><KPI title="Incidentes vinculados" value={n(r.incidents.total, 0)} note="Un movimiento puede tener varios incidentes." icon={<FileText size={18} />} /><KPI title="Incidentes abiertos" value={n(r.incidents.open, 0)} note="Estado registrado al generar el reporte." icon={<Info size={18} />} /><KPI title="Tiempo habitual de cierre" value={mins(r.incidents.medianClose)} note={`${r.incidents.durationN} cierres con tiempo válido; ${r.incidents.missingClose} sin fecha final.`} icon={<Clock3 size={18} />} /></div>
    <Section title="¿Qué descripciones se repiten?" note="Textos iguales agrupados sin distinguir mayúsculas ni espacios repetidos. Son descripciones registradas, no causas diagnosticadas."><label className={styles.search}>Buscar descripción<input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Ejemplo: bandera, lavadero, vía" /></label>{items.length ? <><div className={styles.tableScroll}><table><thead><tr><th>Descripción registrada</th><th>Incidentes</th><th>Movimientos distintos</th><th>Del total de incidentes</th></tr></thead><tbody>{items.slice((page - 1) * 12, page * 12).map(i => <tr key={i.description}><th scope="row">{i.description}</th><td>{i.count}</td><td>{i.movements}</td><td>{pct(i.share)}</td></tr>)}</tbody></table></div><Pager page={page} pages={Math.max(1, Math.ceil(items.length / 12))} total={items.length} setPage={setPage} noun="descripciones" /></> : <Empty>No hay incidentes que coincidan.</Empty>}</Section>
    <p className={styles.note}>Incluye todos los incidentes de los movimientos solicitados en el rango, aunque el incidente se haya registrado después. No se usa la bandera de bloqueo actual como historial.</p>
  </>;
}
function RowDetail({ row, r }: { row: DetailRow; r: Report }) { return <div className={styles.rowDetail}><dl>{[['Solicitud', date(row.requestedAt)], ['Inicio', date(row.startedAt)], ['Fin registrado', date(row.endedAt)], ['Corte de duración', date(row.durationEnd)], ['Retraso del cliente', row.clientDelay === null ? (['DETENIDO', 'CANCELADO'].includes(row.state) ? 'Faltan fechas' : 'No aplica') : timeText(row.clientDelay)], ['Tiempo total desde solicitud', mins(row.elapsed) + (row.elapsedProvisional ? ' · hasta la consulta, sigue aumentando' : '')], ['Reprogramado como', row.reprogrammedTo ? '#' + row.reprogrammedTo : 'Sin referencia'], ['Origen', row.origin], ['Destino', row.destination], ['Cómo se identificó el destino', row.destinationEvidence === 'service' ? 'Servicio marcado en la solicitud; vía de destino sin registrar' : row.destinationEvidence === 'via' ? 'Vía de destino registrada' : row.destinationEvidence === 'ambiguous' ? 'Torno y lavado marcados: confirmar destino' : 'No hay vía ni servicio identificado'], ['Operador registrado', row.operator], ['Supervisor registrado', row.supervisor], ['Coordinador registrado', row.coordinator], ['Duración registrada', mins(row.execution)], ['Cliente asociado', row.client], ['Criterio de duración', bandLabels[row.durationBand]], ['Tiempo coincidente con incidentes', timeText(row.incidentMinutes)]].map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><h4>Revisiones del registro</h4><p>{row.issues.length ? row.issues.map(i => r.quality.find(q => q.key === i)?.label || i).join(' · ') : 'Sin observaciones en las comprobaciones de este reporte.'}</p><h4>Incidentes vinculados</h4>{row.incidents?.length ? row.incidents.map(i => <div className={styles.incident} key={i.id}><b>#{i.id} · {i.state}</b><p>{i.description}</p><small>{date(i.startedAt)} a {date(i.endedAt)}</small></div>) : <p>Sin incidentes registrados.</p>}</div>; }
function DetailReport({ r, initialFilter, initialQuery, initialIssue, initialState, initialGroup }: { r: Report; initialFilter: string; initialQuery: string; initialIssue: string; initialState: string; initialGroup?: ExploreGroup }) {
  const [query, setQuery] = useState(initialQuery), [search, setSearch] = useState(initialQuery), [filter, setFilter] = useState(initialFilter), [state, setState] = useState(initialState), [sort, setSort] = useState(initialFilter === 'short' ? 'shortest' : initialFilter === 'long' ? 'execution' : initialFilter === 'incident' ? 'impact' : 'recent'), [page, setPage] = useState(1), [open, setOpen] = useState<number | null>(null), [issue, setIssue] = useState(initialIssue);
  useEffect(() => { const timer = setTimeout(() => { setSearch(query); setPage(1); }, 300); return () => clearTimeout(timer); }, [query]);
  const [group, setGroup] = useState(initialGroup);
  const params = new URLSearchParams({ page: String(page), q: search, filter, state, sort, ...(issue ? { issue } : {}), ...(group ? { group: group.group, groupKey: group.groupKey } : {}) });
  const { detail, error, loading } = useReportDetail(r.meta.id, params.toString());
  return <Section title="Movimientos que explican las cifras" note="Estos filtros solo cambian la tabla. Excel descarga todos los movimientos del periodo aplicado; PDF incluye el resumen y casos seleccionados."><div className={styles.detailFilters}><label>Buscar<input value={query} onChange={e => setQuery(e.target.value)} placeholder="ID, locomotora, cliente, empresa, vía u operador" /></label><label>Mostrar<select value={filter} onChange={e => { setFilter(e.target.value); setPage(1); }}><option value="all">Todos</option><option value="short">Duración menor de 10 min</option><option value="acceptable">Duración aceptable: 10 a 30</option><option value="long">Duración mayor de 30 min</option><option value="unassessed">Fechas por completar: todos los motivos</option><option value="not_concluded">Abiertos sin corte de duración</option><option value="duration_data">Cerrados con fechas por completar</option><option value="destination_service">Destino identificado por servicio</option><option value="client_delay">Retraso del cliente: detenidos y cancelados</option><option value="client_delay_missing">Retraso del cliente: faltan fechas</option><option value="cancelled_limit">Cancelados por límite de incidentes</option><option value="late">Espera mayor al objetivo</option><option value="incident">Con incidentes</option><option value="pending">Pendientes</option><option value="timing">Revisar fechas o cierre</option><option value="quality">Con datos por revisar</option></select></label><label>Estado<select value={state} onChange={e => { setState(e.target.value); setPage(1); }}><option value="">Todos los estados</option>{r.states.map(s => <option key={s.key} value={s.key}>{s.label}</option>)}</select></label><label>Ordenar<select value={sort} onChange={e => { setSort(e.target.value); setPage(1); }}><option value="recent">Solicitud más reciente</option><option value="execution">Mayor duración</option><option value="shortest">Menor duración</option><option value="impact">Más tiempo con incidentes</option><option value="wait">Mayor espera</option><option value="incidents">Más incidentes</option></select></label></div>
    {group && <div className={styles.notice}>Grupo: {group.label}<button type="button" onClick={() => { setGroup(undefined); setPage(1); }}>Quitar grupo</button></div>}
    {issue && <div className={styles.notice}>Revisión: {r.quality.find(q => q.key === issue)?.label}<button type="button" onClick={() => { setIssue(''); setPage(1); }}>Quitar revisión</button></div>}
    {error && <p role="alert" className={styles.error}>{error}</p>}{loading && <p role="status">Consultando movimientos…</p>}
    {!loading && detail && (detail.rows.length ? <><div className={styles.tableScroll}><table><thead><tr><th>Movimiento / fecha local</th><th>Empresa / cliente</th><th>Estado</th><th>Hasta comenzar</th><th>Duración / criterio</th><th>Retraso del cliente</th><th>Incidentes</th><th>Detalle</th></tr></thead><tbody>{detail.rows.map(row => <DetailTableRow key={row.id} row={row} r={r} open={open === row.id} toggle={() => setOpen(open === row.id ? null : row.id)} />)}</tbody></table></div><Pager page={detail.page} pages={detail.pages} total={detail.total} noun="movimientos" setPage={p => { setPage(p); setOpen(null); }} /></> : <Empty>No hay movimientos que coincidan con esta búsqueda.</Empty>)}
  </Section>;
}
function DetailTableRow({ row, r, open, toggle }: { row: DetailRow; r: Report; open: boolean; toggle: () => void }) { return <><tr><th scope="row">#{row.id}<small>{date(row.requestedAt)}</small></th><td>{row.company}<small>Cliente: {row.client}</small><small>Locomotora {row.locomotive}</small></td><td><span className={styles.badge}>{row.stateLabel}</span></td><td className={row.wait !== null && row.wait > r.meta.target ? styles.attention : ''}>{mins(row.wait)}</td><td>{mins(row.execution)}<small className={styles.bandBadge} data-band={row.durationBand}>{bandLabels[row.durationBand]}</small>{row.durationBand === 'unassessed' && <small>{row.pending ? 'Abierto sin corte de duración' : 'Falta inicio o corte válido'}</small>}</td><td>{row.clientDelay === null ? (['DETENIDO', 'CANCELADO'].includes(row.state) ? 'Faltan fechas' : 'No aplica') : timeText(row.clientDelay)}</td><td>{row.incidentCount}</td><td><button className={styles.textButton} type="button" onClick={toggle} aria-expanded={open} aria-controls={`movement-${row.id}`}>{open ? 'Cerrar' : 'Ver registro'}</button></td></tr>{open && <tr><td colSpan={8} id={`movement-${row.id}`}><RowDetail row={row} r={r} /></td></tr>}</>; }

export default function OperationReport() {
  const { draft, setDraft, applied, report: r, catalogs, loading, error, dirty, apply, download, downloadError, exportReport, expired } = useOperationReport();
  const [tab, setTab] = useState<Tab>('summary'), [focus, setFocus] = useState<{ filter: string; q: string; issue: string; state: string; key: number; group?: ExploreGroup }>({ filter: 'all', q: '', issue: '', state: '', key: 0 });
  const [resource, setResource] = useState('companies');
  const explore: Explore = (filter = 'all', q = '', issue = '', state = '', group) => { setFocus(old => ({ filter, q, issue, state, group, key: old.key + 1 })); setTab('detail'); };
  const preset = (kind: string) => {
    const today = localDay();
    if (kind === 'month') { const first = `${today.slice(0, 7)}-01`, last = shiftDay(first, -1); setDraft(v => ({ ...v, from: `${last.slice(0, 7)}-01`, to: last })); }
    else if (kind === 'history' && r?.meta.firstRequest && r?.meta.lastRequest) { setDraft(v => ({ ...v, from: localDay(new Date(r.meta.firstRequest!)), to: localDay(new Date(r.meta.lastRequest!)) })); }
    else setDraft(v => ({ ...v, from: shiftDay(today, kind === '7' ? -6 : -29), to: today }));
  };
  const change = (key: keyof typeof draft, value: string) => setDraft(v => ({ ...v, [key]: value, ...(key === 'companyId' ? { clientId: '' } : {}) }));
  return <div className={styles.root}>
    <header className={styles.hero}><div><p className={styles.eyebrow}>COSAIF / ADMINISTRACIÓN</p><h1>Entiende tu operación.<br /><span>Decide qué revisar.</span></h1><p>Solicitudes, tiempos e incidentes explicados con los movimientos que los respaldan.</p></div><div className={styles.heroAside}><span>REPORTERÍA OPERATIVA</span><p>Una misma consulta.<br />Pantalla, Excel y PDF.</p><ArrowDownToLine size={28} /></div></header>
    <form className={styles.filters} onSubmit={e => { e.preventDefault(); apply(); }}><div className={styles.filterHeading}><h2>¿Qué periodo quieres entender?</h2><div className={styles.presets}><button type="button" onClick={() => preset('7')}>7 días</button><button type="button" onClick={() => preset('30')}>30 días</button><button type="button" onClick={() => preset('month')}>Mes anterior</button>{r?.meta.firstRequest && <button type="button" onClick={() => preset('history')}>Historial disponible</button>}</div></div><div className={styles.filterGrid}>
      <label>Desde<input type="date" required value={draft.from} max={draft.to} onChange={e => change('from', e.target.value)} /></label><label>Hasta<input type="date" required value={draft.to} min={draft.from} max={localDay()} onChange={e => change('to', e.target.value)} /></label>
      <label>Empresa<select value={draft.companyId} onChange={e => change('companyId', e.target.value)}><option value="">Todas las empresas</option>{catalogs.companies.map(c => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label>
      <label>Cliente asociado<select value={draft.clientId} onChange={e => change('clientId', e.target.value)}><option value="">Todos los clientes</option><option value="unassigned">Sin cliente asociado</option>{catalogs.clients.filter(c => !draft.companyId || c.companyIds.includes(Number(draft.companyId))).map(c => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label>
      <label>Localidad<select value={draft.localityId} onChange={e => change('localityId', e.target.value)}><option value="">Todas las localidades</option>{catalogs.localities.map(c => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label>
      <label>Tipo<select value={draft.type} onChange={e => change('type', e.target.value)}><option value="ALL">Todos los tipos</option><option value="REMOLCADA">Remolcada</option><option value="MD_TRABAJANDO">MD trabajando</option></select></label>
      <label>Objetivo de espera (min)<input type="number" required min="1" max="1440" step="1" value={draft.target} onChange={e => change('target', e.target.value)} /></label>
    </div><div className={styles.filterFooter}><span>Máximo 366 días. Fechas en hora de Ciudad de México.</span><div><button type="button" onClick={() => setDraft(initialFilters())}>Restablecer</button><button type="submit" className={styles.primary} disabled={loading}><RefreshCw size={16} className={loading ? styles.spin : ''} />{loading ? 'Preparando…' : dirty ? 'Aplicar filtros' : 'Actualizar reporte'}</button></div></div></form>
    {dirty && <p className={styles.notice} role="status">Hay filtros sin aplicar. Los resultados siguen mostrando del {applied.from} al {applied.to}. Pulsa Aplicar filtros para actualizarlos.</p>}
    {error && <div role="alert" className={styles.error}><h2>No pudimos preparar el reporte</h2><p>{error}</p><button type="button" onClick={apply}>Volver a intentar</button></div>}
    {loading && <div className={styles.loading} role="status"><RefreshCw className={styles.spin} /><h2>Preparando una lectura de la operación</h2><p>Consultando solicitudes, incidentes y comparación del periodo.</p></div>}
    {!loading && r && <>
      <div className={styles.reportBar}><div><strong>{r.meta.from} al {r.meta.to}</strong><p>{r.meta.company} · {r.meta.client} · {r.meta.locality} · {r.meta.type === 'ALL' ? 'Todos los tipos' : r.meta.type}</p><small>Generado {date(r.meta.generatedAt)} · Consulta {r.meta.id.slice(0, 8)}</small></div><div className={styles.exportButtons}><button type="button" disabled={dirty || expired || !!download} onClick={() => void exportReport('excel')}><FileSpreadsheet size={18} />{download === 'excel' ? 'Preparando Excel…' : 'Descargar Excel'}</button><button type="button" disabled={dirty || expired || !!download} onClick={() => void exportReport('pdf')}><FileText size={18} />{download === 'pdf' ? 'Preparando PDF…' : 'Descargar PDF'}</button><small>Excel: detalle completo. PDF: resumen y casos destacados.</small></div></div>
      {download && <p role="status" className={styles.note}>La descarga usará exactamente las cifras de esta consulta.</p>}{downloadError && <p role="alert" className={styles.error}>{downloadError}</p>}{expired && <p role="status" className={styles.notice}>La consulta venció. Actualiza el reporte para consultar detalle y descargar archivos.</p>}
      {r.meta.warnings.length > 0 && <div className={styles.warnings}><Info size={19} /><div>{r.meta.warnings.map(w => <p key={w}>{w}</p>)}</div></div>}
      <nav className={styles.tabs} aria-label="Secciones del reporte">{tabs.map(t => <button type="button" key={t.id} aria-current={tab === t.id ? 'page' : undefined} onClick={() => setTab(t.id)}>{t.label}</button>)}</nav>
      <div className={styles.content} key={`${r.meta.id}-${tab}`}>
      {tab === 'summary' && <><div className={styles.kpis}><KPI title="Movimientos solicitados" value={n(r.summary.total, 0)} note={`${r.summary.concluded} concluidos y ${r.summary.cancelled} cancelados.`} icon={<TrainFront size={18} />} /><KPI title="Tiempo habitual hasta comenzar" value={mins(r.summary.waitMedian)} note={`${r.summary.waitN} movimientos con espera válida.`} icon={<Clock3 size={18} />} /><KPI title="Duración aceptable: 10 a 30 min" value={pct(r.summary.acceptableRate)} note={`${r.summary.durationAcceptable} de ${r.summary.executionN} intentos evaluados.`} icon={<CheckCircle2 size={18} />} /><KPI title="Movimientos con incidentes" value={pct(r.summary.incidentRate)} note={`${r.summary.affected} de ${r.summary.total} solicitudes, sin duplicados.`} icon={<TriangleAlert size={18} />} /></div>
        <ClientDelaySummary r={r} explore={explore} /><DurationBands metrics={r.summary} explore={explore} />
        {!r.summary.total ? <Empty /> : <><Section title="Qué conviene revisar primero" note="Hallazgos del periodo y un siguiente paso concreto. Abre los movimientos para revisar la evidencia."><div className={styles.insights}>{r.insights.map((i, index) => <article key={i.filter}><span className={styles.step}>{String(index + 1).padStart(2, '0')}</span><div><h3>{i.title}</h3><p>{i.detail}</p><p className={styles.action}>{i.action}</p><button type="button" className={styles.textButton} onClick={() => explore(i.filter)}>Revisar movimientos <ArrowRight size={16} /></button></div></article>)}</div>{!r.insights.length && <p>No se detectaron casos para las revisiones configuradas.</p>}</Section><div className={styles.twoColumns}><Section title="¿Cómo terminaron las solicitudes?" note="Estados registrados al generar el reporte.">{r.states.map(g => <button type="button" className={styles.stateRow} key={g.key} onClick={() => explore('all', '', '', g.key)}><span>{g.label}</span><b>{g.total}</b><span className={styles.stateTrack}><i style={{ width: `${g.total / r.summary.total * 100}%` }} /></span></button>)}<p className={styles.note}>{r.summary.pending} solicitudes seleccionadas siguen pendientes. Usa el detalle para filtrarlas por estado.</p></Section><Section title="¿Cómo cambió la demanda?" note="Solicitudes por día local. Un día sin registros no certifica inactividad."><DailyChart groups={r.days} /></Section></div></>}
        <Comparison report={r} />
      </>}
      {tab === 'times' && <TimeReport r={r} explore={explore} />}
      {tab === 'companies' && <><div className={styles.subnav}>{[['companies', 'Empresas'], ['clients', 'Clientes por empresa'], ['destinations', 'Torno y lavado'], ['vias', 'Vías más utilizadas'], ['routes', 'Rutas'], ['locomotives', 'Locomotoras'], ['operators', 'Operadores']].map(([id, label]) => <button type="button" key={id} aria-pressed={resource === id} onClick={() => setResource(id)}>{label}</button>)}</div>
        {resource === 'clients' && <CompanyClients r={r} explore={explore} />}
        {resource === 'destinations' && <DestinationPanel r={r} explore={explore} />}
        {!['clients', 'destinations'].includes(resource) && <GroupTable key={resource}
          groups={({ companies: r.companies, vias: r.vias, routes: r.routes, locomotives: r.locomotives, operators: r.operators } as Record<string, Group[]>)[resource]}
          title={({ companies: 'Servicio y tiempos por empresa', vias: 'Vías con más solicitudes', routes: 'Rutas de los movimientos', locomotives: 'Historial de locomotoras', operators: 'Movimientos e incidentes por operador asignado' } as Record<string, string>)[resource]}
          note={({ companies: 'Compara cantidad, tasa de incidentes y duración. Abre Clientes por empresa para conocer su desglose.', vias: 'Una solicitud cuenta una vez por vía registrada. Las entradas identificadas por servicio se reúnen en Torno y lavado. Los tiempos son del movimiento completo; no miden ocupación de la vía.', routes: 'Recorridos por origen y destino dentro de la localidad.', locomotives: 'Cada locomotora se distingue dentro de su empresa. Un incidente no confirma una falla mecánica.', operators: 'Ordena por movimientos con incidentes o su tasa. Son movimientos asignados al operador; no identifica al causante del incidente ni evalúa desempeño.' } as Record<string, string>)[resource]}
          onExplore={(g, filter = 'all') => explore(filter, '', '', '', { group: ({ companies: 'company', vias: 'via', routes: 'route', locomotives: 'locomotive', operators: 'operator' } as Record<string, string>)[resource], groupKey: g.key, label: g.label })} />}
        <ImpactSummary r={r} />
      </>}
      {tab === 'incidents' && <><IncidentResolution r={r} explore={explore} /><IncidentReport r={r} /></>}
      {tab === 'detail' && <DetailReport key={focus.key} r={r} initialFilter={focus.filter} initialQuery={focus.q} initialIssue={focus.issue} initialState={focus.state} initialGroup={focus.group} />}
      {tab === 'quality' && <><Section title="¿Qué datos conviene revisar?" note="Un movimiento puede aparecer varias veces. La falta de una vía o un responsable puede ser válida según la operación."><div className={styles.qualityGrid}>{r.quality.map(q => <button key={q.key} type="button" onClick={() => explore('quality', '', q.key)}><span>{q.label}</span><strong>{n(q.count, 0)}</strong><small>Ver registros <ArrowRight size={13} /></small></button>)}</div></Section><Section title="Cómo calculamos los resultados" note="Estas definiciones también se incluyen en Excel y PDF.">{r.methodology.map(m => <details className={styles.definition} key={m.label}><summary>{m.label}</summary><p>{m.text}</p></details>)}</Section><Section title="Cobertura observable" note="Primera y última solicitud con los filtros de empresa, localidad y tipo aplicados."><dl className={styles.coverage}><div><dt>Primera solicitud</dt><dd>{date(r.meta.firstRequest)}</dd></div><div><dt>Última solicitud</dt><dd>{date(r.meta.lastRequest)}</dd></div><div><dt>Fuente</dt><dd>Base principal de Cosaif</dd></div></dl><p className={styles.note}>Torno, Torreón y Comercial tienen fuentes separadas. Este reporte no incorpora costos, facturación ni tiempos de trabajo del personal.</p></Section></>}
      </div>
    </>}
  </div>;
}
