"use client";

import { FormEvent, useMemo, useState } from "react";
import { Mail, Phone, Plus, Search, UsersRound } from "lucide-react";
import type { CrmClient } from "../crmTypes";
import { commercialApi } from "../_lib/api";
import { useCrmList } from "../_lib/useCrmList";
import { useCommercialData } from "../_components/CommercialDataProvider";
import { EmptyPanel, Field, LoadingPanel, Modal, ModuleHeader, Notice } from "../_components/CommercialUi";

export default function CommercialClientsPage() {
  const { analytics } = useCommercialData();
  const { items: clients, loading, error, reload } = useCrmList<CrmClient>("/bff/comercial/clientes?pageSize=100");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<number>();
  const [creating, setCreating] = useState(false);
  const filtered = useMemo(() => clients.filter((item) => `${item.empresaNombre} ${item.razonSocial || ""} ${item.rfc || ""}`.toLowerCase().includes(query.toLowerCase())), [clients, query]);
  const selected = clients.find((item) => item.id === selectedId) ?? filtered[0];
  const companiesWithoutFile = analytics?.catalogs.companies.filter((company) => !clients.some((client) => client.empresaId === company.id)) ?? [];

  return <div className="space-y-5">
    <ModuleHeader eyebrow="Administración de cartera" title="Clientes y contactos" description="Cada cliente tiene su expediente comercial separado de la operación: razón social, condiciones, facturación, cobranza y contactos responsables." icon={UsersRound} actions={<button type="button" onClick={() => setCreating(true)} className="commercial-primary"><Plus className="h-4 w-4"/>Activar cliente</button>}/>
    {error ? <Notice title="La base CRM todavía no está disponible" text="Al ejecutar el push y levantar msComercial se habilitarán los expedientes. La base operativa permanece intacta."/> : null}
    {loading ? <LoadingPanel text="Cargando expedientes comerciales…"/> : <section className="grid gap-4 xl:grid-cols-[340px_1fr]">
      <aside className="commercial-card h-fit p-4"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} className="commercial-input pl-10" placeholder="Buscar cliente, RFC…"/></label><div className="mt-3 space-y-2">{filtered.map((client) => <button key={client.id} type="button" onClick={() => setSelectedId(client.id)} className={`w-full rounded-xl border p-3 text-left transition ${selected?.id === client.id ? "border-emerald-500 bg-emerald-50 dark:bg-emerald-950/20" : "border-[var(--app-border)] hover:bg-[var(--app-surface-muted)]"}`}><p className="font-black text-[var(--app-text)]">{client.empresaNombre}</p><p className="mt-1 text-xs text-[var(--app-text-muted)]">{client.razonSocial || "Razón social pendiente"}</p></button>)}</div></aside>
      {selected ? <article className="commercial-card overflow-hidden"><header className="bg-gradient-to-r from-slate-950 to-emerald-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-[.14em] text-emerald-300">Expediente comercial</p><h2 className="mt-1 text-3xl font-black">{selected.empresaNombre}</h2><p className="mt-2 text-sm text-slate-300">{selected.razonSocial || "Razón social pendiente"}{selected.rfc ? ` · ${selected.rfc}` : ""}</p></header><div className="grid gap-4 p-5 lg:grid-cols-2"><Info title="Condiciones"><Row label="Moneda" value={selected.moneda}/><Row label="Días de crédito" value={`${selected.diasCredito} días`}/><Row label="Orden de compra" value={selected.requiereOrdenCompra ? "Obligatoria" : "No obligatoria"}/><Row label="Estado" value={selected.activo ? "Activo" : "Inactivo"}/></Info><Info title="Facturación y cobranza"><Row label="Facturación" value={selected.correoFacturacion || "Pendiente"}/><Row label="Cobranza" value={selected.correoCobranza || "Pendiente"}/></Info><section className="rounded-2xl border border-[var(--app-border)] p-4 lg:col-span-2"><div className="flex items-center justify-between"><h3 className="font-black text-[var(--app-text)]">Contactos responsables</h3><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black text-slate-700">{selected.contactos.length}</span></div><div className="mt-3 grid gap-3 md:grid-cols-2">{selected.contactos.map((contact) => <div key={contact.id} className="rounded-xl bg-[var(--app-surface-muted)] p-4"><p className="font-black text-[var(--app-text)]">{contact.nombre}</p><p className="text-xs text-[var(--app-text-muted)]">{contact.puesto || contact.tipo}</p><div className="mt-2 space-y-1 text-xs font-bold text-[var(--app-text-muted)]">{contact.email ? <p className="flex gap-2"><Mail className="h-3.5 w-3.5"/>{contact.email}</p> : null}{contact.telefono ? <p className="flex gap-2"><Phone className="h-3.5 w-3.5"/>{contact.telefono}</p> : null}</div></div>)}{!selected.contactos.length ? <p className="text-sm text-[var(--app-text-muted)]">Todavía no hay contactos registrados.</p> : null}</div></section></div></article> : <EmptyPanel title="Seleccione un cliente" text="Abra un expediente para revisar sus datos comerciales y contactos."/>}
    </section>}
    {creating ? <CreateClientModal companies={companiesWithoutFile} onClose={() => setCreating(false)} onCreated={() => { setCreating(false); reload(); }}/> : null}
  </div>;
}

function CreateClientModal({ companies, onClose, onCreated }: { companies: Array<{ id: number; nombre: string }>; onClose: () => void; onCreated: () => void }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const data = new FormData(event.currentTarget); try { await commercialApi("/bff/comercial/clientes", { method: "POST", body: JSON.stringify({ empresaId: Number(data.get("empresaId")), razonSocial: data.get("razonSocial") || null, rfc: data.get("rfc") || null, diasCredito: Number(data.get("diasCredito") || 0), correoFacturacion: data.get("correoFacturacion") || null, correoCobranza: data.get("correoCobranza") || null, requiereOrdenCompra: data.get("requiereOrdenCompra") === "on" }) }); onCreated(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo crear el expediente"); } finally { setSaving(false); } }
  return <Modal title="Activar expediente de cliente" description="No modifica la empresa operativa ni sus movimientos." onClose={onClose}><form onSubmit={submit} className="space-y-4 p-5"><Field label="Empresa operativa"><select name="empresaId" required className="commercial-select"><option value="">Seleccione…</option>{companies.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></Field><Field label="Razón social"><input name="razonSocial" className="commercial-input"/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="RFC"><input name="rfc" minLength={12} maxLength={13} className="commercial-input uppercase"/></Field><Field label="Días de crédito"><input name="diasCredito" type="number" min="0" defaultValue="0" className="commercial-input"/></Field></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Correo de facturación"><input name="correoFacturacion" type="email" className="commercial-input"/></Field><Field label="Correo de cobranza"><input name="correoCobranza" type="email" className="commercial-input"/></Field></div><label className="flex items-center gap-3 rounded-xl bg-[var(--app-surface-muted)] p-4"><input name="requiereOrdenCompra" type="checkbox" className="h-5 w-5"/><span className="text-sm font-black text-[var(--app-text)]">La orden de compra es obligatoria</span></label>{error ? <Notice tone="rose" title="No se pudo guardar" text={error}/> : null}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="commercial-secondary">Cancelar</button><button disabled={saving} className="commercial-primary">{saving ? "Guardando…" : "Guardar expediente"}</button></div></form></Modal>;
}

function Info({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[var(--app-border)] p-4"><h3 className="font-black text-[var(--app-text)]">{title}</h3><div className="mt-3">{children}</div></section>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 border-b border-[var(--app-border)] py-2 text-sm"><span className="text-[var(--app-text-muted)]">{label}</span><span className="text-right font-black text-[var(--app-text)]">{value}</span></div>; }
