"use client";
import { useState, type FormEvent } from "react";
import type { CrmClient } from "../../types";
import { commercialApi } from "../../lib/api";
import { useCrmCatalog } from "../../lib/useCrmList";
import { Field, Modal, Notice } from "../CommercialUi";

export default function CreateClientModal({ companies, onClose, onCreated }: { companies: Array<{ id: number; nombre: string }>; onClose: () => void; onCreated: () => void }) {
  const { items: registered, loading: catalogLoading, error: catalogError } = useCrmCatalog<CrmClient>("/bff/comercial/clientes");
  const availableCompanies = companies.filter(company => !registered.some(client => client.empresaId === company.id));
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const data = new FormData(event.currentTarget); try { await commercialApi("/bff/comercial/clientes", { method: "POST", body: JSON.stringify({ empresaId: Number(data.get("empresaId")), razonSocial: data.get("razonSocial") || null, rfc: data.get("rfc") || null, diasCredito: Number(data.get("diasCredito") || 0), correoFacturacion: data.get("correoFacturacion") || null, correoCobranza: data.get("correoCobranza") || null, requiereOrdenCompra: data.get("requiereOrdenCompra") === "on" }) }); onCreated(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo crear el expediente"); } finally { setSaving(false); } }
  return <Modal title="Activar expediente de cliente" description="No modifica la empresa operativa ni sus movimientos." onClose={onClose}><form onSubmit={submit} className="space-y-4 p-5"><Field label="Empresa operativa"><select name="empresaId" required className="commercial-select"><option value="">Seleccione…</option>{availableCompanies.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></Field><Field label="Razón social"><input name="razonSocial" className="commercial-input"/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="RFC"><input name="rfc" minLength={12} maxLength={13} className="commercial-input uppercase"/></Field><Field label="Días de crédito"><input name="diasCredito" type="number" min="0" defaultValue="0" className="commercial-input"/></Field></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Correo de facturación"><input name="correoFacturacion" type="email" className="commercial-input"/></Field><Field label="Correo de cobranza"><input name="correoCobranza" type="email" className="commercial-input"/></Field></div><label className="flex items-center gap-3 rounded-xl bg-[var(--app-surface-muted)] p-4"><input name="requiereOrdenCompra" type="checkbox" className="h-5 w-5"/><span className="text-sm font-black text-[var(--app-text)]">La orden de compra es obligatoria</span></label>{error || catalogError ? <Notice tone="rose" title="No se pudo guardar" text={error || catalogError}/> : null}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="commercial-secondary">Cancelar</button><button disabled={saving || catalogLoading || !!catalogError} className="commercial-primary">{saving ? "Guardando…" : "Guardar expediente"}</button></div></form></Modal>;
}

